name: Coverage Report

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y lcov cmake gcovr

    - name: Build project and run tests
      run: |
        mkdir build
        cd build
        cmake ..
        make
        ctest

    - name: Generate lcov coverage
      run: |
        cd build
        gcovr -r .. --gcov-executable=gcov --exclude-directories '_deps' --exclude-throw-branches --print-summary --output coverage.info --coveralls coverage.json

    - name: Upload to Coveralls
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: build/coverage.info
