name: Coverage

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install lcov
          pip install coveralls

      - name: Build with coverage
        run: |
          mkdir build && cd build
          cmake -DCODE_COVERAGE=ON ..
          make
          ctest

      - name: Generate lcov report
        run: |
          cd build
          lcov --directory . --capture --output-file coverage.info
          lcov --remove coverage.info '/usr/*' '*/tests/*' --output-file coverage.info

      - name: Upload to Coveralls
        run: |
          coveralls --lcov-file build/coverage.info
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
